model: cnn1d

# 数据集
data_path: dataset/RAVDESS_1s_4categories  # 数据集路径
class_labels: ["neutral","happy","sad","angry"]  # 情感标签

# 特征存储
feature_path: features/  # 特征存储路径
train_feature_path: features/train_cnn1d_opensmile_ravdess_IS10.csv  # 训练特征存储路径
predict_feature_path: features/test_cnn1d_opensmile_ravdess_IS10.csv  # 预测特征存储路径

# Opensmile 配置，只在 'feature_method: o' 时 需要设置
opensmile_config: IS10_paraling  # Opensmile 标准特征集
opensmile_path: E:/Projects/python/opensmile-3.0-win-x64/  # Opensmile 安装路径

# checkpoints
checkpoint_path: checkpoints/  # checkpoint 存储路径
checkpoint_name: CNN1D_OPENSMILE_IS10  # checkpoint 文件名

# 训练参数
epochs: 30  # 训练 epoch 数
batch_size: 32  # 批大小
lr: 0.001  # 学习率

# 模型参数
n_kernels: 32  # 卷积核数量（每个卷积层都一样）
kernel_sizes: [5, 5]  # 每个卷积层的卷积核大小，列表长度为卷积层数量
dropout: 0.5
hidden_size: 32